<a href="https://colab.research.google.com/github/shuvad23/Advanced-Coding-Interview-Preparation-with-Python/blob/main/Advanced_Coding_Interview_Preparation(part01).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Multidimensional Arrays and Their Traversal in Python

- 1. Representing Multidimensional Arrays

In [ ]:
# 1.1 Using Nested Lists
# A 2D array (matrix) can be represented as a list of lists:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# 1.2 Using NumPy (Efficient for Large Data)
import numpy as np

matrix_np = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)
print(matrix_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- 2. Traversing Multidimensional Arrays

In [ ]:

# 2.1 Basic Row-wise Traversal
print("Basic Row-wise Traversal: ")
row = 1
for floor in matrix:
    print(f"row {row}: ",end ="")
    for room in floor:
        print(room,end = ',')
    row +=1
    print()


# 2.2 Column-wise Traversal
print("Column-wise Traversal: ")
column = 1
for col in range(len(matrix[0])):
    print(f"Column {column}: ", end= ' ')
    for row in range(len(matrix)):
        print(matrix[row][col],end = ",")
    column +=1
    print()


# 2.3 Diagonal Traversal (Top-Left to Bottom-Right)
print("Diagonal Traversal (Top-Left to Bottom-Right): ",end = "")
for row in range(len(matrix)):
    print(matrix[row][row],end = ",")
print()



# 2.4 Spiral Order Traversal (Advanced)
def spiral_order_traversal(matrix):
    if matrix is None:
        return []

    top , bottom = 0, len(matrix) -1
    left , right = 0, len(matrix[0]) -1

    while top <= bottom and left <= right:
        # top row
        for i in range(left,right+1):
            yield matrix[top][i]
        top +=1

        # right column
        for j in range(top,bottom+1):
            yield matrix[j][bottom]
        right -=1

        # bottom row
        for k in range(right,left-1,-1):
            yield matrix[bottom][k]
        bottom -=1

        # left column
        for l in range(bottom,top-1,-1):
            yield matrix[l][left]
        left +=1

print("Spiral Order Traversal : ",end = " ")
for element in spiral_order_traversal(matrix):
    print(element,end = ",")
print()

Basic Row-wise Traversal: 
row 1: 1,2,3,
row 2: 4,5,6,
row 3: 7,8,9,
Column-wise Traversal: 
Column 1:  1,4,7,
Column 2:  2,5,8,
Column 3:  3,6,9,
Diagonal Traversal (Top-Left to Bottom-Right): 1,5,9,
Spiral Order Traversal :  1,2,3,6,9,8,7,4,5,


- 3. Real-World Problem: Image Processing (Edge Detection)

In [ ]:
import numpy as np

def sobel_edge_detection(image):
    # Sobel kernels
    sobel_x = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
    sobel_y = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

    # Pad the image to handle borders
    padded = np.pad(image, ((1, 1), (1, 1)), mode='constant')
    # Initialize output
    edge_image = np.zeros_like(image, dtype=np.float32)
    # Convolve with Sobel kernels
    for i in range(1, padded.shape[0] - 1):
        for j in range(1, padded.shape[1] - 1):
            # Extract 3x3 patch
            patch = padded[i-1:i+2, j-1:j+2]

            # Apply Sobel operators
            gx = np.sum(patch * sobel_x)
            gy = np.sum(patch * sobel_y)

            # Compute gradient magnitude
            edge_image[i-1, j-1] = np.sqrt(gx**2 + gy**2)

    return edge_image

# Example usage
image = np.array([
    [100, 100, 100, 100],
    [100, 50, 50, 100],
    [100, 50, 50, 100],
    [100, 100, 100, 100]
])

edges = sobel_edge_detection(image)
print("Edge Detection Result:")
print(edges)

Edge Detection Result:
[[353.5534  254.95097 254.95097 353.5534 ]
 [254.95097 212.13203 212.13203 254.95097]
 [254.95097 212.13203 212.13203 254.95097]
 [353.5534  254.95097 254.95097 353.5534 ]]


4. Key Takeaways

- Nested lists work for small matrices, but NumPy is better for large-scale computations.

- Traversal techniques (row-wise, column-wise, diagonal, spiral) are useful in different scenarios.

- Real-world applications include:

 - Image processing (edge detection, blurring)

 - Game development (grid-based pathfinding)

 - Scientific computing (matrix operations)

### Advanced Multidimensional Array Traversal: Deep Dive with Real-World Applications

- Wave Traversal (Zig-Zag Pattern)

- Rotating a Matrix In-Place

- Pathfinding in Grids (Dijkstra's Algorithm)

- Convolution Operations (Image Filtering)

- 3D Matrix Traversal (Voxel Data Processing)

In [ ]:
# 1. Wave Traversal (Zig-Zag Pattern)

def zig_zag_pattern(matrix):
    if matrix is None:
        return []
    rows = len(matrix)
    cols = len(matrix[0])

    for col in range(cols):
        if col % 2 == 0:
            for row in range(rows):
                yield matrix[row][col]
        else:
            for row in range(rows-1,-1,-1):
                yield matrix[row][col]
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("Zig-Zag Traversal: ",end = " ")
for element in zig_zag_pattern(matrix):
    print(element,end = ",")
print()

Zig-Zag Traversal:  1,4,7,8,5,2,3,6,9,


In [ ]:
# 2. Rotating a Matrix In-Place
def rotate_matrix_90_clockwise(matrix):
    n = len(matrix)

    # Transpose the matrix
    for i in range(n):
        for j in range(i, n):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

    print(matrix)
    # Reverse each row
    for row in matrix:
        row.reverse()

    return matrix

rotated = rotate_matrix_90_clockwise([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(rotated)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [ ]:
# 1. Pathfinding in Grids (Dijkstra's Algorithm) (this code just for my practice using deepseek ) for future study **noted


import heapq
def dijkstra(grid, start, end):
    rows, cols = len(grid), len(grid[0])
    directions = [(0,1), (1,0), (0,-1), (-1,0)]
    heap = [(0, start)]
    visited = set()
    distances = [[float('inf')] * cols for _ in range(rows)]
    distances[start[0]][start[1]] = 0
    predecessors = [[None] * cols for _ in range(rows)]

    while heap:
        dist, (r, c) = heapq.heappop(heap)
        if (r, c) == end:
            break
        if (r, c) in visited:
            continue
        visited.add((r, c))

        for dr, dc in directions:
            nr, nc = r + dr, c + dc
            if 0 <= nr < rows and 0 <= nc < cols:
                new_dist = dist + grid[nr][nc]
                if new_dist < distances[nr][nc]:
                    distances[nr][nc] = new_dist
                    predecessors[nr][nc] = (r, c)
                    heapq.heappush(heap, (new_dist, (nr, nc)))

    # Reconstruct path
    path = []
    if distances[end[0]][end[1]] != float('inf'):
        current = end
        while current != start:
            path.append(current)
            current = predecessors[current[0]][current[1]]
        path.append(start)
        path.reverse()

    return distances[end[0]][end[1]], path

# Weighted grid (higher values = harder to traverse)
grid = [
    [1, 2, 3],
    [4, 8, 2],
    [1, 5, 1]
]

start = (0, 0)
end = (2, 2)
distance, path = dijkstra(grid, start, end)

print(f"Shortest distance: {distance}")
print("Path taken:", path)


# Real-World Applications
#1.  Robotic Navigation: Autonomous robots finding optimal paths in warehouses

#2.  Game AI: NPC movement in strategy games

#3.  Traffic Routing: GPS systems finding least-congested routes

Shortest distance: 8
Path taken: [(0, 0), (0, 1), (0, 2), (1, 2), (2, 2)]


In [ ]:
# 2. Convolution Operations (Image Filtering)
# Advanced Implementation with Multiple Kernels


import numpy as np
from scipy.signal import convolve2d

def apply_filters(image, kernels):
    results = []
    for name, kernel in kernels.items():
        # Add padding to maintain original size
        padded = np.pad(image, ((1,1), (1,1)), mode='constant')
        # Perform convolution
        filtered = convolve2d(padded, kernel, mode='valid')
        results.append((name, filtered))
    return results

# Sample grayscale image (5x5)
image = np.array([
    [50, 60, 70, 80, 90],
    [40, 50, 60, 70, 80],
    [30, 40, 50, 60, 70],
    [20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50]
])

# Collection of common filters
kernels = {
    'blur': np.ones((3,3))/9,
    'sharpen': np.array([[0,-1,0], [-1,5,-1], [0,-1,0]]),
    'edge_detect': np.array([[-1,-1,-1], [-1,8,-1], [-1,-1,-1]]),
    'gaussian': np.array([[1,2,1], [2,4,2], [1,2,1]])/16
}

filtered_images = apply_filters(image, kernels)

for name, result in filtered_images:
    print(f"\n{name} filter:")
    print(np.round(result).astype(int))


# Real-World Applications
#1.  Medical Imaging: Tumor detection in MRI scans

#2.  Autonomous Vehicles: Lane detection in self-driving cars

#3.  Social Media: Instagram/Snapchat filters


blur filter:
[[22 37 43 50 36]
 [30 50 60 70 50]
 [23 40 50 60 43]
 [17 30 40 50 37]
 [ 9 17 23 30 22]]

sharpen filter:
[[150 130 150 170 290]
 [ 70  50  60  70 170]
 [ 50  40  50  60 150]
 [ 30  30  40  50 130]
 [ 10  30  50  70 150]]

edge_detect filter:
[[250 210 240 270 490]
 [ 90   0   0   0 270]
 [ 60   0   0   0 240]
 [ 30   0   0   0 210]
 [ 10  30  60  90 250]]

gaussian filter:
[[28 42 50 58 47]
 [32 50 60 70 58]
 [25 40 50 60 50]
 [18 30 40 50 42]
 [ 9 18 25 32 28]]


In [ ]:
# 3. 3D Matrix Traversal (Voxel Data Processing)
# Volume Rendering with Thresholding

import numpy as np

def process_voxel_data(volume, threshold):
    # Initialize output volume
    segmented = np.zeros_like(volume)

    # Process each voxel
    for z in range(volume.shape[0]):
        for y in range(volume.shape[1]):
            for x in range(volume.shape[2]):
                if volume[z,y,x] > threshold:
                    segmented[z,y,x] = 1  # Mark as tissue
                else:
                    segmented[z,y,x] = 0  # Mark as air

    # Calculate tissue volume
    tissue_voxels = np.sum(segmented)
    total_voxels = volume.size
    percentage = (tissue_voxels / total_voxels) * 100

    return segmented, percentage

# Simulated CT scan data (4 slices of 5x5)
# Values represent density (0-1000 Hounsfield units)
voxel_data = np.random.randint(0, 1000, size=(4,5,5))

# Set bone threshold (typically >400 HU)
threshold = 400
segmented, percentage = process_voxel_data(voxel_data, threshold)

print(f"Original volume:\n{voxel_data}")
print(f"\nSegmented volume (1=tissue, 0=air):\n{segmented}")
print(f"\nTissue occupies {percentage:.2f}% of the volume")

Original volume:
[[[ 43  32 182 995  60]
  [525 724 213 560 571]
  [846 478 262 185 804]
  [ 77 266 214 862  84]
  [464 701 242  97  44]]

 [[994 192  21 412 872]
  [191 129 358 519 921]
  [  4 631 926 785 581]
  [784 628 996 963 286]
  [579 696 395 802 901]]

 [[156 888 799  12 137]
  [525 201 598 410 648]
  [359 420 765 915 553]
  [925 538 925 969 981]
  [947 558 913 451  57]]

 [[622 950 285 412 632]
  [847 651 461 715 542]
  [116 182 341 401 558]
  [753 710 806 138 555]
  [727 220   5 710  54]]]

Segmented volume (1=tissue, 0=air):
[[[0 0 0 1 0]
  [1 1 0 1 1]
  [1 1 0 0 1]
  [0 0 0 1 0]
  [1 1 0 0 0]]

 [[1 0 0 1 1]
  [0 0 0 1 1]
  [0 1 1 1 1]
  [1 1 1 1 0]
  [1 1 0 1 1]]

 [[0 1 1 0 0]
  [1 0 1 1 1]
  [0 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 0]]

 [[1 1 0 1 1]
  [1 1 1 1 1]
  [0 0 0 1 1]
  [1 1 1 0 1]
  [1 0 0 1 0]]]

Tissue occupies 64.00% of the volume


In [ ]:
# Advanced Application: Marching Cubes Algorithm


from skimage.measure import marching_cubes

def generate_3d_surface(volume, threshold):
    # Run marching cubes
    verts, faces, normals, values = marching_cubes(volume, threshold)

    # Calculate surface area and volume
    surface_area = marching_cubes(volume, threshold)[2]
    volume = np.sum(volume > threshold)

    return verts, faces, surface_area, volume

# Example usage with medical data
# (In practice, you'd load real DICOM data)
verts, faces, area, vol = generate_3d_surface(voxel_data, threshold)
print(f"\nGenerated {len(faces)} triangles")
print(f"Surface area: {area} voxel units")
print(f"Tissue volume: {vol} voxels")

# Real-World Applications
#1.  Medical Diagnostics: Tumor volume measurement

#2.  Geological Surveying: Oil reservoir modeling

#3.  3D Printing: STL file generation from scans


Generated 114 triangles
Surface area: [[-3.66654128e-01  2.81825095e-01  8.86645019e-01]
 [ 4.29924637e-01  6.39671862e-01  6.37169302e-01]
 [-9.51368093e-01  3.81835707e-04  3.08056146e-01]
 [-5.31657264e-02 -9.92651224e-01  1.08705573e-01]
 [ 2.84589767e-01 -9.34923172e-01 -2.11960644e-01]
 [ 9.83841181e-01 -1.75483808e-01  3.55244987e-02]
 [ 8.49456191e-01 -4.94056493e-01 -1.85290024e-01]
 [ 3.80321532e-01 -3.30586165e-01  8.63752484e-01]
 [ 3.17637801e-01  1.08855821e-01 -9.41942990e-01]
 [-1.37479782e-01  4.60889727e-01 -8.76743972e-01]
 [ 7.76130378e-01 -1.76584765e-01 -6.05342388e-01]
 [-1.32895470e-01 -8.89782071e-01 -4.36608076e-01]
 [-3.05496186e-01 -1.67421386e-01  9.37359154e-01]
 [-8.63974214e-01 -3.37877482e-01  3.73346150e-01]
 [-5.97899079e-01  2.89677948e-01  7.47397780e-01]
 [ 3.01369250e-01 -2.27845579e-01 -9.25884962e-01]
 [ 1.19031690e-01 -7.03590155e-01 -7.00565755e-01]
 [ 6.70635462e-01 -4.40304250e-01 -5.96975923e-01]
 [-8.87269914e-01  1.62551910e-01  4.316583