<a href="https://colab.research.google.com/github/shuvad23/Advanced-Coding-Interview-Preparation-with-Python/blob/main/Advanced_Coding_Interview_Preparation(part01).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Multidimensional Arrays and Their Traversal in Python

## Unit 1:
- 1. Representing Multidimensional Arrays

In [ ]:
# 1.1 Using Nested Lists
# A 2D array (matrix) can be represented as a list of lists:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# 1.2 Using NumPy (Efficient for Large Data)
import numpy as np

matrix_np = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)
print(matrix_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- 2. Traversing Multidimensional Arrays

In [ ]:

# 2.1 Basic Row-wise Traversal
print("Basic Row-wise Traversal: ")
row = 1
for floor in matrix:
    print(f"row {row}: ",end ="")
    for room in floor:
        print(room,end = ',')
    row +=1
    print()


# 2.2 Column-wise Traversal
print("Column-wise Traversal: ")
column = 1
for col in range(len(matrix[0])):
    print(f"Column {column}: ", end= ' ')
    for row in range(len(matrix)):
        print(matrix[row][col],end = ",")
    column +=1
    print()


# 2.3 Diagonal Traversal (Top-Left to Bottom-Right)
print("Diagonal Traversal (Top-Left to Bottom-Right): ",end = "")
for row in range(len(matrix)):
    print(matrix[row][row],end = ",")
print()



# 2.4 Spiral Order Traversal (Advanced)
def spiral_order_traversal(matrix):
    if matrix is None:
        return []

    top , bottom = 0, len(matrix) -1
    left , right = 0, len(matrix[0]) -1

    while top <= bottom and left <= right:
        # top row
        for i in range(left,right+1):
            yield matrix[top][i]
        top +=1

        # right column
        for j in range(top,bottom+1):
            yield matrix[j][bottom]
        right -=1

        # bottom row
        for k in range(right,left-1,-1):
            yield matrix[bottom][k]
        bottom -=1

        # left column
        for l in range(bottom,top-1,-1):
            yield matrix[l][left]
        left +=1

print("Spiral Order Traversal : ",end = " ")
for element in spiral_order_traversal(matrix):
    print(element,end = ",")
print()

Basic Row-wise Traversal: 
row 1: 1,2,3,
row 2: 4,5,6,
row 3: 7,8,9,
Column-wise Traversal: 
Column 1:  1,4,7,
Column 2:  2,5,8,
Column 3:  3,6,9,
Diagonal Traversal (Top-Left to Bottom-Right): 1,5,9,
Spiral Order Traversal :  1,2,3,6,9,8,7,4,5,


- 3. Real-World Problem: Image Processing (Edge Detection)

In [ ]:
import numpy as np

def sobel_edge_detection(image):
    # Sobel kernels
    sobel_x = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
    sobel_y = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

    # Pad the image to handle borders
    padded = np.pad(image, ((1, 1), (1, 1)), mode='constant')
    # Initialize output
    edge_image = np.zeros_like(image, dtype=np.float32)
    # Convolve with Sobel kernels
    for i in range(1, padded.shape[0] - 1):
        for j in range(1, padded.shape[1] - 1):
            # Extract 3x3 patch
            patch = padded[i-1:i+2, j-1:j+2]

            # Apply Sobel operators
            gx = np.sum(patch * sobel_x)
            gy = np.sum(patch * sobel_y)

            # Compute gradient magnitude
            edge_image[i-1, j-1] = np.sqrt(gx**2 + gy**2)

    return edge_image

# Example usage
image = np.array([
    [100, 100, 100, 100],
    [100, 50, 50, 100],
    [100, 50, 50, 100],
    [100, 100, 100, 100]
])

edges = sobel_edge_detection(image)
print("Edge Detection Result:")
print(edges)

Edge Detection Result:
[[353.5534  254.95097 254.95097 353.5534 ]
 [254.95097 212.13203 212.13203 254.95097]
 [254.95097 212.13203 212.13203 254.95097]
 [353.5534  254.95097 254.95097 353.5534 ]]


4. Key Takeaways

- Nested lists work for small matrices, but NumPy is better for large-scale computations.

- Traversal techniques (row-wise, column-wise, diagonal, spiral) are useful in different scenarios.

- Real-world applications include:

 - Image processing (edge detection, blurring)

 - Game development (grid-based pathfinding)

 - Scientific computing (matrix operations)

### Advanced Multidimensional Array Traversal: Deep Dive with Real-World Applications

- Wave Traversal (Zig-Zag Pattern)

- Rotating a Matrix In-Place

- Pathfinding in Grids (Dijkstra's Algorithm)

- Convolution Operations (Image Filtering)

- 3D Matrix Traversal (Voxel Data Processing)

In [ ]:
# 1. Wave Traversal (Zig-Zag Pattern)

def zig_zag_pattern(matrix):
    if matrix is None:
        return []
    rows = len(matrix)
    cols = len(matrix[0])

    for col in range(cols):
        if col % 2 == 0:
            for row in range(rows):
                yield matrix[row][col]
        else:
            for row in range(rows-1,-1,-1):
                yield matrix[row][col]
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("Zig-Zag Traversal: ",end = " ")
for element in zig_zag_pattern(matrix):
    print(element,end = ",")
print()

Zig-Zag Traversal:  1,4,7,8,5,2,3,6,9,


In [ ]:
# 2. Rotating a Matrix In-Place
def rotate_matrix_90_clockwise(matrix):
    n = len(matrix)

    # Transpose the matrix
    for i in range(n):
        for j in range(i, n):
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

    print(matrix)
    # Reverse each row
    for row in matrix:
        row.reverse()

    return matrix

rotated = rotate_matrix_90_clockwise([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(rotated)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[7, 4, 1], [8, 5, 2], [9, 6, 3]]


In [ ]:
# 1. Pathfinding in Grids (Dijkstra's Algorithm) (this code just for my practice using deepseek ) for future study **noted


import heapq
def dijkstra(grid, start, end):
    rows, cols = len(grid), len(grid[0])
    directions = [(0,1), (1,0), (0,-1), (-1,0)]
    heap = [(0, start)]
    visited = set()
    distances = [[float('inf')] * cols for _ in range(rows)]
    distances[start[0]][start[1]] = 0
    predecessors = [[None] * cols for _ in range(rows)]

    while heap:
        dist, (r, c) = heapq.heappop(heap)
        if (r, c) == end:
            break
        if (r, c) in visited:
            continue
        visited.add((r, c))

        for dr, dc in directions:
            nr, nc = r + dr, c + dc
            if 0 <= nr < rows and 0 <= nc < cols:
                new_dist = dist + grid[nr][nc]
                if new_dist < distances[nr][nc]:
                    distances[nr][nc] = new_dist
                    predecessors[nr][nc] = (r, c)
                    heapq.heappush(heap, (new_dist, (nr, nc)))

    # Reconstruct path
    path = []
    if distances[end[0]][end[1]] != float('inf'):
        current = end
        while current != start:
            path.append(current)
            current = predecessors[current[0]][current[1]]
        path.append(start)
        path.reverse()

    return distances[end[0]][end[1]], path

# Weighted grid (higher values = harder to traverse)
grid = [
    [1, 2, 3],
    [4, 8, 2],
    [1, 5, 1]
]

start = (0, 0)
end = (2, 2)
distance, path = dijkstra(grid, start, end)

print(f"Shortest distance: {distance}")
print("Path taken:", path)


# Real-World Applications
#1.  Robotic Navigation: Autonomous robots finding optimal paths in warehouses

#2.  Game AI: NPC movement in strategy games

#3.  Traffic Routing: GPS systems finding least-congested routes

Shortest distance: 8
Path taken: [(0, 0), (0, 1), (0, 2), (1, 2), (2, 2)]


>This code takes a 3D image (like a CT scan), extracts a surface where the tissue is present (using a threshold), and estimates the shape and size of that tissue.

>It’s a powerful tool for analyzing and visualizing 3D structures in medical and scientific applications.

In [ ]:
# 2. Convolution Operations (Image Filtering)
# Advanced Implementation with Multiple Kernels


import numpy as np
from scipy.signal import convolve2d

def apply_filters(image, kernels):
    results = []
    for name, kernel in kernels.items():
        # Add padding to maintain original size
        padded = np.pad(image, ((1,1), (1,1)), mode='constant')
        # Perform convolution
        filtered = convolve2d(padded, kernel, mode='valid')
        results.append((name, filtered))
    return results

# Sample grayscale image (5x5)
image = np.array([
    [50, 60, 70, 80, 90],
    [40, 50, 60, 70, 80],
    [30, 40, 50, 60, 70],
    [20, 30, 40, 50, 60],
    [10, 20, 30, 40, 50]
])

# Collection of common filters
kernels = {
    'blur': np.ones((3,3))/9,
    'sharpen': np.array([[0,-1,0], [-1,5,-1], [0,-1,0]]),
    'edge_detect': np.array([[-1,-1,-1], [-1,8,-1], [-1,-1,-1]]),
    'gaussian': np.array([[1,2,1], [2,4,2], [1,2,1]])/16
}

filtered_images = apply_filters(image, kernels)

for name, result in filtered_images:
    print(f"\n{name} filter:")
    print(np.round(result).astype(int))


# Real-World Applications
#1.  Medical Imaging: Tumor detection in MRI scans

#2.  Autonomous Vehicles: Lane detection in self-driving cars

#3.  Social Media: Instagram/Snapchat filters


blur filter:
[[22 37 43 50 36]
 [30 50 60 70 50]
 [23 40 50 60 43]
 [17 30 40 50 37]
 [ 9 17 23 30 22]]

sharpen filter:
[[150 130 150 170 290]
 [ 70  50  60  70 170]
 [ 50  40  50  60 150]
 [ 30  30  40  50 130]
 [ 10  30  50  70 150]]

edge_detect filter:
[[250 210 240 270 490]
 [ 90   0   0   0 270]
 [ 60   0   0   0 240]
 [ 30   0   0   0 210]
 [ 10  30  60  90 250]]

gaussian filter:
[[28 42 50 58 47]
 [32 50 60 70 58]
 [25 40 50 60 50]
 [18 30 40 50 42]
 [ 9 18 25 32 28]]


In [ ]:
# 3. 3D Matrix Traversal (Voxel Data Processing)
# Volume Rendering with Thresholding

import numpy as np

def process_voxel_data(volume, threshold):
    # Initialize output volume
    segmented = np.zeros_like(volume)

    # Process each voxel
    for z in range(volume.shape[0]):
        for y in range(volume.shape[1]):
            for x in range(volume.shape[2]):
                if volume[z,y,x] > threshold:
                    segmented[z,y,x] = 1  # Mark as tissue
                else:
                    segmented[z,y,x] = 0  # Mark as air

    # Calculate tissue volume
    tissue_voxels = np.sum(segmented)
    total_voxels = volume.size
    percentage = (tissue_voxels / total_voxels) * 100

    return segmented, percentage

# Simulated CT scan data (4 slices of 5x5)
# Values represent density (0-1000 Hounsfield units)
voxel_data = np.random.randint(0, 1000, size=(4,5,5))

# Set bone threshold (typically >400 HU)
threshold = 400
segmented, percentage = process_voxel_data(voxel_data, threshold)

print(f"Original volume:\n{voxel_data}")
print(f"\nSegmented volume (1=tissue, 0=air):\n{segmented}")
print(f"\nTissue occupies {percentage:.2f}% of the volume")

Original volume:
[[[367 495 219  87 689]
  [496 654 473  41 474]
  [446 951 300 345 476]
  [833 804 500 948 939]
  [358 870 530 998 664]]

 [[276 879 666 280 778]
  [ 31 730 626 235 319]
  [942 766 703 561 428]
  [ 26 589  90  91 741]
  [778 427 588 651 999]]

 [[508 132 431 245 229]
  [375 618 427 979 961]
  [157 941 806 349 770]
  [227 213 188 811 370]
  [995 213 233 645 891]]

 [[413 557 917  96 193]
  [616 384 637 799 161]
  [613 295 812 543 217]
  [941 864 299 288 881]
  [876 104 881 590 920]]]

Segmented volume (1=tissue, 0=air):
[[[0 1 0 0 1]
  [1 1 1 0 1]
  [1 1 0 0 1]
  [1 1 1 1 1]
  [0 1 1 1 1]]

 [[0 1 1 0 1]
  [0 1 1 0 0]
  [1 1 1 1 1]
  [0 1 0 0 1]
  [1 1 1 1 1]]

 [[1 0 1 0 0]
  [0 1 1 1 1]
  [0 1 1 0 1]
  [0 0 0 1 0]
  [1 0 0 1 1]]

 [[1 1 1 0 0]
  [1 0 1 1 0]
  [1 0 1 1 0]
  [1 1 0 0 1]
  [1 0 1 1 1]]]

Tissue occupies 64.00% of the volume


In [ ]:
# Advanced Application: Marching Cubes Algorithm


from skimage.measure import marching_cubes

def generate_3d_surface(volume, threshold):
    # Run marching cubes
    verts, faces, normals, values = marching_cubes(volume, threshold)

    # Calculate surface area and volume
    surface_area = marching_cubes(volume, threshold)[2]
    volume = np.sum(volume > threshold)

    return verts, faces, surface_area, volume

# Example usage with medical data
# (In practice, you'd load real DICOM data)
verts, faces, area, vol = generate_3d_surface(voxel_data, threshold)
print(f"\nGenerated {len(faces)} triangles")
print(f"Surface area: {area} voxel units")
# Proper surface area calculation
def compute_surface_area(verts, faces):
    area = 0
    for tri in faces:
        a, b, c = verts[tri]
        ab = b - a
        ac = c - a
        area += 0.5 * np.linalg.norm(np.cross(ab, ac))
    return area
print(f"Surface area: {compute_surface_area(verts, faces)} voxel units")
print(f"Tissue volume: {vol} voxels")

# 🔬 Why is this code important?
#-  Especially in medical imaging, this is useful for:

#-  3D Reconstruction: Turn 2D scans (like slices from CT/MRI) into 3D shapes.

#-  Volume Analysis: Measure how much space a tumor or organ takes up.

#-  Surface Measurement: Calculate surface area of anatomical structures.

#-  Visualization: Doctors or radiologists can view 3D models for diagnosis or surgery planning.

#-  AI and Simulation: Feed structured 3D data into machine learning or surgical simulations.




# Real-World Applications
#1.  Medical Diagnostics: Tumor volume measurement

#2.  Geological Surveying: Oil reservoir modeling

#3.  3D Printing: STL file generation from scans


Generated 139 triangles
Surface area: [[ 2.43169919e-01 -6.88395798e-01 -6.83359087e-01]
 [ 5.49197793e-01 -3.44219774e-01 -7.61508048e-01]
 [ 9.56077203e-02 -1.10902414e-01 -9.89221811e-01]
 [-1.65652603e-01 -7.19953001e-01 -6.73963547e-01]
 [-3.52109484e-02  3.49726260e-01 -9.36190009e-01]
 [-7.70111322e-01 -3.63902688e-01  5.23930728e-01]
 [-8.51387262e-01 -2.57040918e-01  4.57241446e-01]
 [-6.00332975e-01 -3.02643955e-01  7.40274906e-01]
 [-3.71044129e-01  9.37783569e-02  9.23867881e-01]
 [-3.57969820e-01  1.04435369e-01  9.27874386e-01]
 [-4.79306012e-01 -1.01594880e-01  8.71747792e-01]
 [-8.69357049e-01  2.96936631e-01 -3.95027786e-01]
 [-1.74102247e-01  9.67709497e-02 -9.79961097e-01]
 [ 2.45179757e-01 -1.02893189e-01 -9.64002013e-01]
 [ 5.41753471e-02  2.78717488e-01 -9.58843887e-01]
 [-2.19765618e-01  2.11764261e-01 -9.52291429e-01]
 [-1.01069987e-01 -8.45889986e-01 -5.23693562e-01]
 [-2.96264678e-01 -8.35974365e-02  9.51440334e-01]
 [-7.35744178e-01 -4.09061462e-01  5.397677

## unit 2

- Columnar ZigZag and Reverse Traversal of Matrices

In [ ]:
# Columnar ZigZag and Reverse Traversal of Matrices
def columnar_zigzag_traversal(matrix):
    if matrix is None:
        return []
    rows = len(matrix)
    cols = len(matrix[0])

    for col in range(cols-1,-1,-1):
        if col % 2 == 0:
            for row in range(rows):
                yield matrix[row][col]
        else:
            for row in range(rows-1,-1,-1):
                yield matrix[row][col]
    return matrix
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
print("Columnar ZigZag Traversal: ",end = " ")
for element in columnar_zigzag_traversal(matrix):
    print(element,end = ",")
print()

Columnar ZigZag Traversal:  12,8,4,3,7,11,10,6,2,1,5,9,


In [ ]:
# more optimized way to solve this problem
def columnar_zigzag_traversal(matrix):
    if matrix is None:
        return []
    rows = len(matrix)
    cols = len(matrix[0])
    direction = 'up'
    row , col = rows - 1, cols -1
    result = []

    while len(result) < rows * cols :
        result.append(matrix[row][col])

        if direction == 'up':
            if row -1 < 0:
                direction = 'down'
                col -=1
            else:
                row -=1
        else:
            if row + 1 == rows:
                direction = 'up'
                col -=1
            else:
                row +=1
    return result
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
print("Columnar ZigZag Traversal: ",end = " ")
for element in columnar_zigzag_traversal(matrix):
    print(element,end = ",")
print()

Columnar ZigZag Traversal:  12,8,4,3,7,11,10,6,2,1,5,9,


- Traverse Using Decreasing Range

In [ ]:
def traverse_decreasing_range(matrix):
    if matrix is None:
        return []
    rows = len(matrix)-1
    cols = len(matrix[0]) -1

    while rows> -1:
        for col in range(cols,-1,-1):
            yield matrix[rows][col]
        rows -=1
    return matrix

matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
print("Traverse Using Decreasing Range: ",end = " ")
for element in traverse_decreasing_range(matrix):
    print(element,end = ",")
print()

Traverse Using Decreasing Range:  12,11,10,9,8,7,6,5,4,3,2,1,


## Unit 3

>Matrix transposition is a fundamental operation where rows become columns and vice versa. Let's explore advanced problems and optimized solutions beyond the basic numpy.transpose().

In [ ]:
# Transposing Matrices in Python
def transposing_matrix(matrix):
    # if matrix is None:
    #     return []
    # rows = len(matrix)
    # cols = len(matrix[0])
    # result_matirx = [[0 for _ in range(rows)] for _ in range(cols)]
    # for row in range(rows):
    #     for col in range(cols):
    #         result_matirx[col][row] = matrix[row][col]
    # return result_matirx

    # alternative solution
    if matrix is None:
        return []
    rows = len(matrix)
    cols = len(matrix[0])
    result_matirx = [[matrix[row][col] for row in range(rows)] for col in range(cols)]
    return result_matirx
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
print(transposing_matrix(matrix))

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [ ]:
# 1. Basic Transposition
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
# zip(*matrix) unpacks rows into columns.
transposed = list(zip(*matrix))
print(transposed)



[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]


In [ ]:
# 2. Transposition with List Comprehension
matrix= [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

transposed = [[row[col] for row in matrix] for col in range(len(matrix[0]))]
print(transposed)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


In [ ]:
# 3. In-Place Transposition (Square Matrix)
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

for row in range(len(matrix)):
    for col in range(row + 1, len(matrix)):
        matrix[row][col],matrix[col][row] = matrix[col][row], matrix[row][col]
print(matrix)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [ ]:
# 4. Transposition for Sparse Matrices
# Efficiently transpose a sparse matrix (mostly zeros).

from collections import defaultdict
sparse = [
    [0, 0, 3],
    [0, 5, 0],
    [7, 0, 0]
]

transpose = defaultdict(int)
for row in range(len(sparse)):
    for col in range(len(sparse)):
        if sparse[row][col] != 0:
            transpose[(col,row)] = sparse[row][col]
print(transpose)

defaultdict(<class 'int'>, {(2, 0): 3, (1, 1): 5, (0, 2): 7})


In [ ]:
# 5. Blockwise Transposition (Large Matrices)
# Transpose a large matrix in blocks (memory-efficient).
import numpy as np

large_matrix = np.random.rand(1000,1000)
block_size = 100
transposed = np.empty_like(large_matrix)
# this is main matrix ----
print(large_matrix)

for i in range(0, 1000,block_size):
    for j in range(0, 1000, block_size):
        transposed[i:i+block_size, j:j+block_size] = large_matrix[j:j+block_size, i:i+block_size].T
# this one is transposed matrix
print(transposed)


# Note :
# Use Case: GPU acceleration (CUDA) for big data.

[[0.51921241 0.19465805 0.32357217 ... 0.55529248 0.246045   0.34916514]
 [0.34956295 0.76397393 0.46088172 ... 0.89085817 0.26114942 0.53485916]
 [0.47898875 0.30353518 0.33079139 ... 0.64134455 0.80154596 0.62763711]
 ...
 [0.69495889 0.99884347 0.96075031 ... 0.58856337 0.36511455 0.02469284]
 [0.96383025 0.78617923 0.6203443  ... 0.47775026 0.57132637 0.44433164]
 [0.64144489 0.86887865 0.82236133 ... 0.76129848 0.7062186  0.53081623]]
[[0.51921241 0.34956295 0.47898875 ... 0.69495889 0.96383025 0.64144489]
 [0.19465805 0.76397393 0.30353518 ... 0.99884347 0.78617923 0.86887865]
 [0.32357217 0.46088172 0.33079139 ... 0.96075031 0.6203443  0.82236133]
 ...
 [0.55529248 0.89085817 0.64134455 ... 0.58856337 0.47775026 0.76129848]
 [0.246045   0.26114942 0.80154596 ... 0.36511455 0.57132637 0.7062186 ]
 [0.34916514 0.53485916 0.62763711 ... 0.02469284 0.44433164 0.53081623]]


In [ ]:
# 6. Transposition in Linear Algebra
# Problem:
# Verify if (Aᵀ)ᵀ = A.

A = [[1, 2], [3, 4]]
A_transpose = list(zip(*A))
print(A_transpose)
A_transpose_transpose = list(zip(*A_transpose))
print(A_transpose_transpose)

# Note:
# Math Insight:
# Double transposition returns the original matrix.

[(1, 3), (2, 4)]
[(1, 2), (3, 4)]


In [ ]:
# 7. Parallel Transposition (Multithreading)
# Problem:
# Speed up transposition using parallel processing.

from concurrent.futures import ThreadPoolExecutor
import numpy as np
def transpose_chunk(chunk):
    return list(zip(*chunk))

matrix = np.random.rand(1000,1000)
chunks = np.array_split(matrix,4)  # Split into 4 chunks

with ThreadPoolExecutor() as executor:
    results = list(executor.map(transpose_chunk,chunks))
final_response = np.vstack(results)
print(final_response.shape)


# Performance Gain:
# 4x faster on a quad-core CPU.

(4000, 250)


In [ ]:
# 8. Transposition in Image Processing
# Problem:
# Rotate an image (represented as a matrix) 90° clockwise.

image = [
    [1, 2, 3],
    [4, 5, 6]
]

rotated = list(zip(*image[::-1]))  # Transpose + reverse rows
print(rotated)  # [(4, 1), (5, 2), (6, 3)]

[(4, 1), (5, 2), (6, 3)]


>Adjacent Cells in 2D Arrays (Matrices/Grids)

>Adjacent cells (or neighboring cells) in a 2D array are the cells that are directly next to a given cell, either:
- Horizontally or vertically (4-directional adjacency)
- Including diagonals (8-directional adjacency)

[1] [2] [3]

[4] [5] [6]

[7] [8] [9]

- 4-directional adjacent cells (up, down, left, right):

[2] (above)

[4] (left)

[6] (right)

[8] (below)

- 8-directional adjacent cells (includes diagonals):

>All 4-directional neighbors plus:

[1] (top-left)

[3] (top-right)

[7] (bottom-left)

[9] (bottom-right)

1 Key Concepts
- 4-directional adjacency (von Neumann neighborhood):

    Up, Down, Left, Right

    Used in maze solving, simple pathfinding

    8-directional adjacency (Moore neighborhood):

    Includes diagonals

    Used in image processing, more complex pathfinding

2. Edge handling:

    Corner cells have only 3 adjacent cells (8-directional)

    Edge cells (not corners) have 5 adjacent cells

    Center cells in a 3x3 grid have all 8 adjacent cells

- Task Statement
>Visualize a chessboard in the form of a 2D array, where each cell could be marked 'E' for empty or 'P' for a piece. Our quest involves summoning a Python function named find_positions(). Upon examining this 2D array, this function identifies all the spots where a new piece could be placed so that it can move to another empty cell in one move. The catch is that a piece can move only to an immediately neighboring cell directly above, below, to the left, or right, but not diagonally.

In [ ]:
def find_positions(board):
    positions = []
    rows, cols = len(board), len(board[0])

    for row in range(rows):
        for col in range(cols):
            if board[row][col] == 'E':
                if((col < cols -1 and board[row][col+1] == "E") or
                  (col > 0 and board[row][col-1] == "E") or
                  (row < rows -1 and board[row+1][col] == "E") or
                  (row > 0 and board[row-1][col] == "E")):
                  positions.append((row,col))

    return positions
board = [
    ['P', 'E', 'E', 'P'],
    ['E', 'P', 'E', 'P'],
    ['P', 'E', 'P', 'P'],
    ['P', 'E', 'P', 'E']
]

print(find_positions(board))

[(0, 1), (0, 2), (1, 2), (2, 1), (3, 1)]


- Lesson : 05
> Navigating Adjacent Cells in a Grid: An Exercise in 2D Traversal

In [ ]:
def path_traverse(grid, start_row, start_col):
    if not grid or not grid[0]:
        return []
    rows, cols = len(grid), len(grid[0])
    visited = [[False for _ in range(cols)] for _ in range(rows)]
    directions = [(0, 1), (0, -1), (1, 0), (-1, 0)]  # Right, Left, Down, Up

    def dfs(row, col):
        if row < 0 or row >= rows or col < 0 or col >= cols:
            return []
        if visited[row][col] or grid[row][col] != 0:
            return []

        visited[row][col] = True
        path = [(row, col)]

        for dr, dc in directions:
            new_row, new_col = row + dr, col + dc
            path.extend(dfs(new_row, new_col))
        return path

    return dfs(start_row, start_col)

grid = [
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 1, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]
]
start_row, start_col = 1, 2
print(path_traverse(grid, start_row, start_col))

[[False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False]]
[[False, False, False, False, False], [False, False, True, False, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False]]
[[False, False, False, False, False], [False, False, True, True, False], [False, False, False, False, False], [False, False, False, False, False], [False, False, False, False, False]]
[[False, False, False, False, False], [False, False, True, True, False], [False, False, False, True, False], [False, False, False, False, False], [False, False, False, False, False]]
[[False, False, False, False, False], [False, False, True, True, False], [False, False, False, True, False], [False, False, False, True, False], [False, False, False, False, False]]
[[False, False, False, False, False], [False, False, True, True, False], [False,

In [5]:
def path_traversed(grid, start_row, start_col):
    if not grid or not grid[0]:
        return []

    rows, cols = len(grid), len(grid[0])
    directions = [(0, 1), (0, -1), (1, 0), (-1, 0)]  # Right, Left, Down, Up
    path = [grid[start_row][start_col]]

    x,y = start_row, start_col

    while True:
        possible_move = []
        current_position = grid[x][y]
        for dr,dc in directions:
            new_row, new_col = x + dr, y + dc
            if 0 <= new_row < rows and 0 <= new_col < cols and current_position < grid[new_row][new_col]:
                possible_move.append((new_row,new_col))

        if not possible_move:
            break

        next_position = max(possible_move,key = lambda pos : grid[pos[0]][pos[1]])

        x,y = next_position
        path.append(grid[x][y])

    return path


mountain = [
    [1,2,3,4,5],
    [6,8,9,11,10],
    [7,12,13,14,15]
]

print(path_traversed(mountain,0,0))

[1, 6, 8, 12, 13, 14, 15]
